schema_version: 1

context:
  version: "1.1.6"
  python_min: "3.10"

package:
  name: sfincs-jax
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sfincs-jax/sfincs_jax-${{ version }}.tar.gz
  sha256: c4bfe14737465c5c7b8e20b96cf7ed3471417c4dd0f775b57195bcbd79b98b22

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sfincs_jax = sfincs_jax.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - jax
    - numpy
    - scipy
    - h5py
    - netcdf4
    - matplotlib-base

tests:
  - python:
      imports:
        - sfincs_jax
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - sfincs_jax --help

about:
  summary: Neoclassical transport solver with CPU/GPU and differentiable JAX workflows
  license: MIT
  license_file: LICENSE
  homepage: https://sfincs-jax.readthedocs.io/
  repository: https://github.com/uwplasma/sfincs_jax
  documentation: https://sfincs-jax.readthedocs.io/

extra:
  recipe-maintainers:
    - rogeriojorge
    - matthewfeickert
